### ISSUE TITLE
depositToken function too much costly in gaz

### ISSUE THREAD

**Issue by bitcoin4cashqc** [william2958/ERC20TokenExchange#1]
Compiling and deploying the code in Remix work, then I try to deposit token on, but I get :+1: 

`TokenExchange.depositToken errored: Gas required exceeds limit: 4000000.  An important gas estimation might also be the sign of a problem in the contract code. Please check loops and be sure you did not sent value to a non payable function (that's also the reason of strong gas estimation). `

Any Help? I see this repo was last edited not so long ago, I'm sure I make a mistake or forget something. I've found near nothing about!

**Comment by bitcoin4cashqc** [comment]
[contract.txt](https://github.com/william2958/ERC20TokenExchange/files/1503625/contract.txt)

**Comment by bitcoin4cashqc** [comment]
Oups wrong contract, quite bad

**Comment by william2958** [comment]
You should usually not try and run more complex contracts on Remix, on my development server I have Truffle configured to allow a maximum gas of 9000000 on my development server. Try to replicate the project as is, and run it locally instead of the browser.

**Comment by bitcoin4cashqc** [comment]
but, isn't that mean contract would be explensive to use using real ETH ?

________________________________
De : William Huang <notifications@github.com>
Envoyé : 26 novembre 2017 04:26:43
À : william2958/ERC20TokenExchange
Cc : bitcoin4cashqc; State change
Objet : Re: [william2958/ERC20TokenExchange] depositToken function too much costly in gaz (#1)


You should usually not try and run more complex contracts on Remix, on my development server I have Truffle configured to allow a maximum gas of 9000000 on my development server. Try to replicate the project as is, and run it locally instead of the browser.

**Comment by william2958** [comment]
Yes, but since this was just more of a learning experiment it is ok to use uncapped gas. In production projects you would have to consider these things much more. 9000000 is a gross overestimation of what the gas would be required, maybe you can try and edit the application to work on Remix if you would like. Or perhaps there was a bug somewhere along the way. Anyway, this project is just to show what is possible with smart contracts, and not actually for deployment on the live net. Happy coding!
